
name: CI/CD with docker

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t "docker.pkg.github.com/git-buch/api:$GITHUB_SHA" .
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      - name: Push image to GitHub
        run: docker push "docker.pkg.github.com/git-buch/ci-docker/api:$GITHUB_SHA"
