
name: CI/CD with docker

on:
  push:
    branches: [ master ]

env:
  API_IMG: "docker.pkg.github.com/git-buch/ci-docker/api"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t "${API_IMG}:${GITHUB_SHA}" .
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Push image to GitHub
        run: docker push "${API_IMG}:${GITHUB_SHA}"
  test:
    runs-on: ubuntu-latest
    services:
      api:
        image: "${API_IMG}:${GITHUB_SHA}"
        ports: 3001:3001
    steps:
      - uses: actions/checkout@v2
      - name: test running container
        run: |
          npm install
          npm test
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build docker image
        run: |
          docker pull "${API_IMG}:${GITHUB_SHA}"
          docker tag "${API_IMG}:latest" "${API_IMG}:${GITHUB_SHA}"
          docker push "${API_IMG}:latest"

