
name: CI/CD with docker

on:
  push:
    branches: [ master ]

env:
  API_IMG: "docker.pkg.github.com/git-buch/ci-docker/api:$GITHUB_SHA"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t "$API_IMG" .
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Push image to GitHub
        run: docker push "$API_IMG"
